# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ruangan', '0001_initial'),
        ('peminjam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_bayar', models.DateTimeField(blank=True, null=True)),
                ('deskripsi', models.CharField(blank=True, max_length=1000)),
                ('tipe', models.CharField(choices=[('B', 'Belum Lunas'), ('S', 'Sudah Lunas')], db_index=True, default='B', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_awal', models.DateTimeField(db_index=True)),
                ('waktu_akhir', models.DateTimeField(db_index=True)),
                ('deskripsi', models.CharField(blank=True, max_length=1000)),
                ('peminjam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peminjam.Peminjam')),
                ('ruangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruangan.Ruangan')),
            ],
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='peminjaman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peminjaman.Peminjaman'),
        ),
    ]
