# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import peminjaman.models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0002_auto_20170407_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjaman',
            name='foto',
            field=models.ImageField(blank=True, max_length=500, upload_to=peminjaman.models.peminjaman_foto_dir),
        ),
    ]
