# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import ruangan.models


class Migration(migrations.Migration):

    dependencies = [
        ('ruangan', '0002_auto_20170324_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruangan',
            name='foto',
            field=models.ImageField(blank=True, max_length=500, upload_to=ruangan.models.ruangan_foto_dir),
        ),
    ]
