# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruangan', '0003_ruangan_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruangan',
            name='warna',
            field=models.CharField(default=b'#FFFFFF', max_length=10),
        ),
    ]
