# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruangan', '0004_ruangan_warna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruangan',
            name='warna',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
