# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peminjam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(db_index=True, max_length=250, unique=True)),
                ('deskripsi', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
